---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "ahmadalli/rancher-local-path-provisioner"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
